# Generated by Django 3.2.8 on 2021-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imabor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='urls',
            field=models.CharField(max_length=200),
        ),
    ]
