# Generated by Django 3.2.8 on 2021-11-20 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imabor', '0006_alter_image_asseturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='asseturl',
        ),
    ]
