# Generated by Django 3.2.8 on 2021-12-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imabor', '0008_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='subtags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
